#!/usr/bin/env Rscript

library(data.table)
library(stringr)
library(optparse)

# This script extracts all numerical values and structures from a folder of .fold files 
# generated by RNAfold and returns a comprehensive CSV file.

# --- Command-Line Argument Parsing ---
option_list <- list(
  make_option(c("-i", "--input"), type="character", default=NULL, 
              help="Input directory containing .fold files", metavar="DIRECTORY"),
  make_option(c("-o", "--output"), type="character", default=NULL, 
              help="Output directory for the CSV files", metavar="DIRECTORY")
)

opt_parser <- OptionParser(option_list=option_list)
opt <- parse_args(opt_parser)

if (is.null(opt$input) || is.null(opt$output)) {
  print_help(opt_parser)
  stop("Input and output directories must be specified.", call.=FALSE)
}

print("Started")

input_directory <- opt$input
output_directory <- opt$output

dir.create(output_directory, showWarnings = FALSE, recursive = TRUE)
file_list <- list.files(path = input_directory, pattern = "\\.fold$", full.names = TRUE)

# --- Core Extraction Function ---

extract_fold_info <- function(file_path) {
  tryCatch({
    lines <- readLines(file_path)
    
    if (length(lines) < 7) {
      stop("File does not contain enough lines for full parsing.")
    }
    
    # Define a robust regex for parsing numbers, including scientific notation
    num_regex <- "[-]?\\d*\\.?\\d+(?:[eE][-+]?\\d+)?"

    # --- Line-by-Line Extraction (Corrected based on new format) ---
    
    # Lines 1 & 2: ID and Sequence
    sequence_id <- sub(">", "", lines[1])
    sequence <- lines[2]
    
    # Line 3: MFE (Minimum Free Energy)
    mfe_structure <- str_extract(lines[3], "^[().]+")
    mfe_energy <- as.numeric(str_extract(lines[3], sprintf("(?<=\\()\\s*(%s)(?=\\s*\\)$)", num_regex)))
    
    # Line 4: Probabilistic Dot-Plot Representation
    dot_plot_representation <- str_extract(lines[4], "^[().|,{}]+")
    dot_plot_energy <- as.numeric(str_extract(lines[4], sprintf("(?<=\\[)\\s*(%s)(?=\\s*\\]$)", num_regex)))
    
    # Line 5: Centroid Structure
    centroid_structure <- str_extract(lines[5], "^[().]+")
    centroid_energy <- as.numeric(str_extract(lines[5], sprintf("(?<=\\{)\\s*(%s)", num_regex)))
    centroid_distance <- as.numeric(str_extract(lines[5], sprintf("(?<=d=)\\s*(%s)(?=\\s*\\})", num_regex)))
    
    # Line 6: MEA (Maximum Expected Accuracy) Structure
    mea_structure <- str_extract(lines[6], "^[().]+")
    mea_energy <- as.numeric(str_extract(lines[6], sprintf("(?<=\\{)\\s*(%s)(?=\\s+MEA=)", num_regex)))
    mea_score <- as.numeric(str_extract(lines[6], sprintf("(?<=MEA=)\\s*(%s)(?=\\s*\\})", num_regex)))
    
    # Line 7: Ensemble Statistics
    numbers_in_line7 <- str_extract_all(lines[7], num_regex)[[1]]
    mfe_frequency <- as.numeric(numbers_in_line7[1])
    ensemble_diversity <- as.numeric(numbers_in_line7[2])
    
    # --- Validation and Result Assembly ---
    essential_values <- c(mfe_structure, mfe_energy, centroid_structure, centroid_energy, 
                          mea_structure, mea_energy, mea_score, 
                          mfe_frequency, ensemble_diversity)
    if (any(is.na(essential_values))) {
      stop("Failed to extract one or more essential values. Check file format.")
    }
    
    result <- data.table(
      sequence_id = sequence_id,
      sequence = sequence,
      mfe_structure = mfe_structure,
      mfe_energy = mfe_energy,
      dot_plot_representation = dot_plot_representation,
      dot_plot_energy = dot_plot_energy,
      centroid_structure = centroid_structure,
      centroid_energy = centroid_energy,
      centroid_distance = centroid_distance,
      mea_structure = mea_structure,
      mea_energy = mea_energy,
      mea_score = mea_score,
      mfe_frequency = mfe_frequency,
      ensemble_diversity = ensemble_diversity
    )
    
    return(result)
    
  }, error = function(e) {
    return(list(file_name = basename(file_path), error_message = e$message))
  })
}

# --- Main Processing Loop ---
print(paste("Processing", length(file_list), "files..."))

results_list <- lapply(file_list, extract_fold_info)

is_error <- sapply(results_list, function(x) "error_message" %in% names(x))
failed_files_list <- results_list[is_error]
successful_results <- results_list[!is_error]

master_data_table <- rbindlist(successful_results, use.names = TRUE, fill = TRUE)
failed_files_df <- rbindlist(failed_files_list, use.names = TRUE, fill = TRUE)
if (nrow(failed_files_df) == 0) {
    failed_files_df <- data.frame(file_name=character(), error_message=character())
}

# --- Output and Summary ---
output_file <- file.path(output_directory, "RNAfold_fold_summary.csv")
fwrite(master_data_table, output_file)
print(paste("Success! Output written to", output_file))

if (nrow(failed_files_df) > 0) {
    failed_files_output <- file.path(output_directory, "RNAfold_fold_failed_files.csv")
    fwrite(failed_files_df, failed_files_output)
    print(paste("Failed files log written to", failed_files_output))
}

print("--- Summary ---")
print(paste("Total files found:", length(file_list)))
print(paste("Successfully processed files:", nrow(master_data_table)))
print(paste("Failed files:", nrow(failed_files_df)))